"""create quotes table

Revision ID: bfe2eda9cce0
Revises: 
Create Date: 2023-12-13 14:09:27.598871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe2eda9cce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade(engine_name: str) -> None:
#     globals()["upgrade_%s" % engine_name]()


# def downgrade(engine_name: str) -> None:
#     globals()["downgrade_%s" % engine_name]()





# def upgrade_postgres_engine() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('quotes',
#     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#     sa.Column('quote', sa.Text(), nullable=False),
#     sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
#     sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True),
#     sa.PrimaryKeyConstraint('id', name=op.f('quotes_pkey'))
#     )
#     # ### end Alembic commands ###


# def downgrade_postgres_engine() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('quotes')
#     # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('created_tstamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_tstamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quotes_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###

